export const SERIES_PRESETS = [
  'Action Fleet : Classic Vessel',
  'Action Fleet : Alpha Series',
  'Action Fleet : Transforming Playsets',
  'Action Fleet : Sonderserie',
  'Action Fleet : Battle Packs',
  'Action Fleet Episode 1 : Single Packs',
  'Action Fleet Episode 1 : Mini-Scenes',
  'Action Fleet Episode 1 : Alpha Series',
  'Action Fleet Episode 1 : Playsets',
  'Action Fleet Episode 1 : Miscellaneous',
  'Hasbro Saga Action Fleet 2002 : Vessel',
  'Hasbro Saga Action Fleet 2002 : Battle Packs',
  'Micro Machines : Playsets',
  'Micro Machines : Transforming Action Sets',
  'Micro Machines : Mini Figures',
  'Micro Machines : Original 3 Pack Filme',
  'Micro Machines : Original 3 Pack',
  'Micro Machines : Mini Heads',
  'Micro Machines : Gift Sets',
  'Micro Machines : X-Ray',
  'Micro Machines : Die Cast',
  'Micro Machines : Epic Collections',
] as const

export type SeriesPreset = (typeof SERIES_PRESETS)[number]
